services:
  mongodb:
    image: mongo:7
    container_name: codexhotel-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: codexHotel
    restart: unless-stopped

  app:
    image: oladayoajomole/codexhotel:latest
    container_name: codexhotel-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/codexHotel
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      PAYSTACK_SECRET_KEY: ${PAYSTACK_SECRET_KEY}
      PAYSTACK_PUBLIC_KEY: ${PAYSTACK_PUBLIC_KEY}
      PAYSTACK_BASE_URL: ${PAYSTACK_BASE_URL}
    restart: unless-stopped

volumes:
  mongo-data:
