spring.application.name=codexHotel
spring.data.mongodb.uri=mongodb://localhost:27017/codexHotel
server.port=8080
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/v3/api-docs
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
paystack.secret-key=sk_test_5cc9a9d65fc38b24bbd5af9478f03e93d7e28e69
paystack.public-key=pk_test_effce37b562aab7169099e062f59f1e6c5ef5a2c