spring.application.name=codexHotel
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=codexHotel
server.port=8080
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.use-management-port=false
springdoc.swagger-ui.enabled=true
springdoc.scalar.enabled=true
springdoc.scalar.path=/scalar