spring.application.name=${MONGO_URI}
spring.data.mongodb.uri=${MONGO_DATABASE}
server.port=8080
springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html